-- 실습. DDL
CREATE TABLE MEMBER (
	ID VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(5) NOT NULL,
	AGE INT,
	GENDER VARCHAR(2) NOT NULL,
    EMAIL VARCHAR(50),
    PROMOTION VARCHAR(2) DEFAULT 'X'
	);

-- 실습. DDL(2)
ALTER TABLE MEMBER MODIFY ID VARCHAR(10);
ALTER TABLE MEMBER DROP AGE;
ALTER TABLE MEMBER ADD INTEREST VARCHAR(100);    

-- 실습.CREATE 문
CREATE TABLE USER (
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	PW VARCHAR(20) NOT NULL,
	NAME VARCHAR(5) NOT NULL,
	GENDER ENUM('F','M','') DEFAULT '',
    BIRTHDAY DATE NOT NULL,
    AGE INT(3) NOT NULL DEFAULT 0
	);

-- 실습. INSERT 문
INSERT INTO USER VALUES
		('hong1234', '8o4bkg', '홍길동', 'M', '1990-01-31','33'),
        ('sexysung', '87awjkdf', '성춘향', 'F', '1992-03-31','31'),
        ('power70', 'qxur8sda', '변사또', 'M', '1970-05-02','53'),
        ('hanjo', 'jk48fn4', '한조', 'M', '1984-10-18','39'),
        ('widowmaker', '38ewifh3', '위도우', 'F', '1976-06-27','47'),
        ('dvadva', 'k3f3ah', '송하나', 'F', '2001-06-03','22'),
        ('jungkrat', '4ifha7f', '정크랫', 'M', '1999-11-11','24');

-- 실습.SELECT 문
SELECT * FROM USER;

SELECT * FROM USER ORDER BY BIRTHDAY ASC;
SELECT * FROM USER WHERE GENDER = 'M' ORDER BY NAME DESC;


SELECT ID, NAME FROM USER WHERE BIRTHDAY   LIKE '199%';

SELECT * FROM USER WHERE BIRTHDAY LIKE '%-06-%' ORDER BY BIRTHDAY ASC;

SELECT * FROM USER WHERE GENDER = 'M' AND BIRTHDAY LIKE '197%';

SELECT *FROM USER ORDER BY AGE DESC LIMIT 3;

SELECT * FROM USER WHERE AGE BETWEEN 25 AND 50;

UPDATE USER SET PW = '12345678' WHERE ID = 'hong1234';

DELETE FROM USER WHERE ID = 'jungkrat';


-- 확인용
        
DROP TABLE MEMBER;
DESC MEMBER;
DESC USER;